config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flights#index"

  resources :flights, only: [:index] do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[show]
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :seats, dependent: :destroy
  has_many :flights

  validates :model, presence: true
end

app/models/airport.rb
class Airport < ApplicationRecord
  belongs_to :city
  has_many :departure_flights, foreign_key: :departure_airport_id, class_name: 'Flight'
  has_many :arrival_flights, foreign_key: :arrival_airport_id, class_name: 'Flight'

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :booking_passengers
  has_many :passengers, through: :booking_passengers
  has_one :invoice
  belongs_to :user
  belongs_to :flight

  validates :number, presence: true, uniqueness: true

  accepts_nested_attributes_for :flight, :passengers
end

app/models/booking_passenger.rb
class BookingPassenger < ApplicationRecord
  belongs_to :booking
  belongs_to :passenger
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :airports
  has_many :departure_flights, through: :airports
  has_many :arrival_flights, through: :airports

  validates :name, presence: true

  def self.all_cities_with_country_symbol
    left_joins(:country).select('cities.id', 'cities.name', 'countries.symbol as country_symbol')
  end
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities

  validates :name, presence: true, uniqueness: true
  validates :symbol, presence: true, uniqueness: true
end

app/models/deaperture_flight.rb
class DeapertureFlight < ApplicationRecord
  belongs_to :airport
  belongs_to :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airplane
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  belongs_to :departure_city, class_name: 'City'
  belongs_to :arrival_city, class_name: 'City'
  has_many :bookings

  validates :number, presence: true, uniqueness: true
  validates :departure_date, presence: true
  validates :arrival_date, presence: true
  validates :price, presence: true

  scope :available, -> { where('available = ? AND departure_date >= ?', true, Date.today + 4.hours) }
  scope :by_departure_date, ->(date) { where('departure_date >= ? AND departure_date < ?', date, date + 1.day) }
  scope :by_departure_city, ->(departure_city_id) { where(departure_city_id:) }
  scope :by_arrival_city, ->(arrival_city_id) { where(arrival_city_id:) }

  def self.search_departure_flights_for(filter_params)
    flights = Flight.available
    if filter_params[:departure_date].present?
      flights = flights.by_departure_date(filter_params[:departure_date].to_date)
    end
    flights = flights.by_departure_city(filter_params[:departure_city_id]) if filter_params[:departure_city_id].present?
    flights = flights.by_arrival_city(filter_params[:arrival_city_id]) if filter_params[:arrival_city_id].present?

    flights
  end

  def available_seats
    airplane.seats.availables
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :booking

  validates :total_amount, presence: true
  validates :paid, inclusion: { in: %w[true false] }, presence: true
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :user, optional: true
  has_many :booking_passengers
  has_many :bookings, through: :booking_passengers

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :identification_number, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :airplane

  validates :name, presence: true, uniqueness: { scope: :airplane_id }
  validates :available, presence: true
  validates :price, presence: true

  scope :availables, -> { where(available: true) }
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :airplane

  validates :name, presence: true, uniqueness: { scope: :airplane_id }
  validates :available, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :passenger
  has_many :bookings
  has_many :invoices, through: :bookings
  has_many :flights, through: :bookings

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @booking = Bookings::Creator.with_just_amount_of_passengers(
      flight:,
      amount_of_passengers: params[:amount_of_passengers].to_i,
      user: current_user
    ).build
  end

  def create
    booking_creator.build
    booking = booking_creator.commit
    redirect_to booking_path(booking)

    SendBookingMailToPassengersJob.perform_later(booking)
  rescue StandardError => e
    redirect_to_booking_with_notice(e.message)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_creator
    @booking_creator ||= Bookings::Creator.new(
      flight:,
      booking_build_params: booking_params.to_h,
      user: current_user
    )
  end

  def current_user_passenger
    @current_user_passenger || current_user.passenger
  end

  def flight
    @flight ||= Flight.find(params[:flight_id])
  end

  def amount_of_passengers
    params[:amount_of_passengers].to_i
  end

  def redirect_to_booking_with_notice(message)
    redirect_to(
      new_flight_booking_path(flight, { amount_of_passengers: params[:amount_of_passengers] }),
      alert: message
    )
  end

  def booking_params
    params.require(:booking).permit(
      passengers_attributes: %i[id
                                first_name
                                last_name
                                identification_number
                                email]
    )
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    return redirect_to_booking if params[:submit_flight_id]
    return flights unless flights.empty?

    render_empty_list_message
  end

  private

  def flights
    @flights ||= Flight.search_departure_flights_for(params)
  end

  def redirect_to_booking
    redirect_to new_flight_booking_path(flight, { amount_of_passengers: params[:amount_of_passengers] })
  end

  def render_empty_list_message
    render turbo_stream: turbo_stream.update(
      'flights-index-list'.to_sym,
      'NO FLIGHTS FOR THIS FILTER'
    )
  end

  def flight
    @flight ||= Flight.find(flight_id)
  end

  def flight_id
    params[:submit_flight_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="min-w-full min-h-full flex flex-col gap-3">
  <h2 class="text-xl font-bold inline-block">Flight information:</h2>
  <span class="inline-block">
    <span class="font-bold inline">number:</span>
    <span class="inline">
      <%=  @booking.flight.number %>
    </span>
  </span>
  <span class="inline-block">
    <span class="font-bold inline">departure city/airport:</span>
    <span class="inline">
      <%= "#{ @booking.flight.departure_city.name }/#{ @booking.flight.departure_airport.name }" %>
    </span>
  </span>
  <span class="inline-block">
    <span class="font-bold inline">departure date:</span>
    <span class="inline">
      <%= "#{ @booking.flight.departure_date }" %>
    </span>
  </span>
  <span class="inline-block">
    <span class="font-bold inline">arrival city/airport:</span>
    <span class="inline">
      <%= "#{ @booking.flight.arrival_city.name }/#{ @booking.flight.arrival_airport.name }" %>
    </span>
  </span>
  <span class="inline-block">
    <span class="font-bold inline">arrival date:</span>
    <span class="inline">
      <%= "#{ @booking.flight.arrival_date }" %>
    </span>
  </span>
  <span class="inline-block">
    <span class="font-bold inline">seats:</span>
    <span class="inline">
      <%= "#{ params[:amount_of_passengers] }" %>
    </span>
  </span>
  <%= form_with(
    model: @booking,
    url: flight_bookings_path(
      @booking.flight,
      { amount_of_passengers: @booking.passengers.size }
    ),
    data: {
      turbo: false,
    },
    method: :post,
    class: "min-w-full min-h-full flex flex-col gap-3 justify-between py-6"
  ) do |form|%>

    <%= form.fields_for :passengers do |passenger| %>
      <%= render(
        partial: 'partials/passenger_form_fields',
        locals: { passenger: },
        current_user:
      ) %>
    <% end %>

    <div class='min-w-full flex justify-end'>
      <%= form.submit('Next Step', { class: 'btn-next'}) %>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
bookings#show  <%= @booking.number %>

app/views/flights/index.html.erb
flights#index

<%= form_with(url: flights_path, method: :get) do |f| %>
  <div class="min-w-full flex flex-col gap-4 mt-6">
    <div class="min-w-full flex gap-4">
      <div class="w-1/2 flex flex-col gap-2">
        <%= f.label :departure_city_id %>
        <%= f.select(
          :departure_city_id,
          City.all_cities_with_country_symbol.map {|city| ["#{city.name} (#{city.country_symbol})", city.id]},
          { prompt: 'Select daperture city', selected: params[:departure_city_id] }, { class: 'w-full' }
        ) %>
      </div>
      <div class="w-1/2 flex flex-col gap-2">
        <%= f.label :arrival_city_id %>
        <%= f.select(
          :arrival_city_id,
          City.all_cities_with_country_symbol.map {|city| ["#{city.name} (#{city.country_symbol})", city.id]},
          { prompt: 'Select arrival city' }, { class: 'w-full' }
        ) %>
      </div>
    </div>
    <div class="w-full flex flex-col gap-2">
      <%= f.label :departure_date %>
      <%= f.date_field(
        :departure_date,
        class: 'w-full',
        value: params[:departure_date]
      ) %>
    </div>
    <div class="w-full flex flex-col gap-2">
      <%= f.label :amount_of_passengers %>
      <%= f.number_field(
        :amount_of_passengers,
        class: 'w-full',
        value: params[:amount_of_passengers] || 1
      ) %>
    </div>
    <div class="min-w-full">
      <%= f.submit 'Search', class: 'w-full' %>
    </div>
  </div>


  <div class="min-w-full">
    <%= link_to "Clear filter", flights_path, class: 'w-full' %>
  </div>

  <div id="flights-index-list" class="min-w-full flex flex-col gap-4 mt-6">
    <%= render(
      partial: 'partials/flights/list',
      locals: {
        flights: @flights,
        form: f
      }
    ) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TOPFlightsBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="min-w-full sticky h-10">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <div>
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
        <% else %>
          <%= link_to "Sign in", user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_passenger_form_fields.erb
<% if passenger.options[:child_index] == 0 %>
  <h3 class="text-xl font-bold">
    <%= "Passenger #{passenger.options[:child_index] + 1}(logged-in user) information" %>
  </h3>
<% else %>
  <h3 class="text-xl font-bold">
    <%= "Passenger #{passenger.options[:child_index] + 1} information" %>
  </h3>
<% end %>

<div class="min-h-full flex flex-col gap-2 mb-3">
  <%= passenger.label :first_name, "first name:" %>
  <%= passenger.text_field(
    :first_name,
    placeholder: Faker::Name.first_name
  ) %>
</div>
<div class="min-h-full flex flex-col gap-2 mb-3">
  <%= passenger.label :last_name, "last name:" %>
  <%= passenger.text_field(
    :last_name,
    placeholder: Faker::Name.last_name
  ) %>
</div>
<div class="min-h-full flex flex-col gap-2 mb-3">
  <%= passenger.label :identification_number, "personal identification number:" %>
  <%= passenger.text_field(
    :identification_number,
    placeholder: Faker::IDNumber.valid
  ) %>
</div>
<div class="min-h-full flex flex-col gap-2 mb-3">
  <%= passenger.label :email, "e-mail:" %>
  <%= passenger.email_field(
    :email,
    placeholder: Faker::Internet.email
  ) %>
</div>

app/views/partials/flights/_card.html.erb
<div class="min-w-full">
  <%= flight.departure_city.name %> to <%= flight.arrival_city.name %>
  <div class="min-w-full flex justify-between">
    <div class="w-1/3 flex flex-col">
      <span class="block">
        fligth number: <%= flight.number %>
      </span>
      <span class="block">
        price: <%= flight.price %>
      </span>
    </div>
    <div class="w-2/3 flex flex-col">
      <span class="block">
        daperture airport: <%= flight.departure_airport.name %> | daperture date: <%= flight.departure_date %>
      </span>
      <span class="block">
        arrival airport: <%= flight.arrival_airport.name %> | arrival date: <%= flight.arrival_date %>
      </span>
    </div>
    <%= form.button("BOOK THIS FLIGHT", type: :submit, name: "submit_flight_id", value: flight.id) %>
  </div>
</div>

app/views/partials/flights/_list.html.erb
<% flights.each do |flight| %>
  <%= render partial: 'partials/flights/card', locals: { flight:, form: } %>
<% end %>